[system.packages :: distribution == 'debian']
pip=python3-pip


[system :: distribution == 'debian']
install=sudo apt-get --yes --option APT::Status-Fd=2 install ${package}
progress_re=pmstatus:.*?:(?P<percent>[^:]+):.*
check=sh -c 'dpkg --list ${package} | grep "ii  *${package}\\b"'
remove=sudo apt-get --yes remove ${package}
