[system.packages :: distribution == 'debian']
dbus-send=dbus
dconf=dconf-cli
libpoppler-glib=libpoppler-glib-dev
pip=python3-pip
python-gi-cairo=python3-gi-cairo


[system :: distribution == 'debian']
check=sh -c 'dpkg --list ${package} | grep "ii  *${package}\\b"'
install=sudo apt-get --yes --option APT::Status-Fd=2 install ${package}
progress_re=pmstatus:.*?:(?P<percent>[^:]+):.*
remove=sudo apt-get --yes remove ${package}
