[package_names :: distribution == 'debian']
dbus-send=dbus
dconf=dconf-cli
pip=python3-pip
vim=vim-nox


[commands :: distribution == 'debian']
package_install=sudo apt-get --yes install ${package}
package_check=sh -c 'dpkg --list ${package} | grep "ii  *${package}\\b"'
package_remove=sudo apt-get --yes remove ${package}

[commands :: distribution == 'fedora' and version < '22']
package_install=sudo yum --assumeyes install ${package}
package_check=rpm -q ${package}
package_remove=sudo yum --assumeyes remove ${package}

[commands :: distribution == 'fedora' and version >= '22']
package_install=sudo dnf --assumeyes install ${package}
package_check=rpm -q ${package}
package_remove=sudo dnf --assumeyes remove ${package}

[commands :: distribution == 'macos']
package_install=brew install ${package}
package_check=brew list ${package}
package_remove=brew uninstall ${package}

[commands :: distribution == 'rhel' and version < '8']
package_install=sudo yum --assumeyes install ${package}
package_check=rpm -q ${package}
package_remove=sudo yum --assumeyes remove ${package}

[commands :: distribution == 'rhel' and version >= '8']
package_install=sudo dnf --assumeyes install ${package}
package_check=rpm -q ${package}
package_remove=sudo dnf --assumeyes remove ${package}

[commands :: distribution == 'termux']
package_install=apt-get --yes install ${package}
package_check=dpkg --status ${package}
package_remove=apt-get --yes remove ${package}
